### ISSUE TITLE
SDDEProblem issue with Julia v1.8?  ERROR: too many parameters for type.

### ISSUE THREAD

**Issue by Jamesafross** [SciML/StochasticDelayDiffEq.jl#54] opened 2022-08-19 10:03 UTC
Hello.

Running the example from the SciML page (https://diffeq.sciml.ai/stable/solvers/sdde_solve/) results in the following error for me.

> ERROR: too many parameters for type
> Stacktrace:
>  [1] (SDDEFunction{true, true})(f::typeof(hayes_modelf), g::typeof(hayes_modelg); mass_matrix::LinearAlgebra.UniformScaling{Bool}, analytic::Nothing, tgrad::Nothing, jac::Nothing, jvp::Nothing, vjp::Nothing, jac_prototype::Nothing, sparsity::Nothing, Wfact::Nothing, Wfact_t::Nothing, paramjac::Nothing, ggprime::Nothing, syms::Nothing, observed::typeof(SciMLBase.DEFAULT_OBSERVED), colorvec::Nothing, sys::Nothing)
>    @ SciMLBase ~/.julia/packages/SciMLBase/OfgnG/src/scimlfunctions.jl:2724
>  [2] SDDEFunction(f::Function, g::Function; kwargs::Base.Pairs{Symbol, Union{Nothing, typeof(SciMLBase.DEFAULT_OBSERVED)}, NTuple{12, Symbol}, NamedTuple{(:analytic, :tgrad, :jac, :jvp, :vjp, :Wfact, :Wfact_t, :paramjac, :syms, :observed, :colorvec, :sys), Tuple{Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}}})
>    @ SciMLBase ~/.julia/packages/SciMLBase/OfgnG/src/scimlfunctions.jl:2788
>  [3] convert(#unused#::Type{SDDEFunction}, f::Function, g::Function)
>    @ SciMLBase ~/.julia/packages/SciMLBase/OfgnG/src/scimlfunctions.jl:3726
>  [4] SDDEProblem(::Function, ::Function, ::Vector{Float64}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Tuple{Float64}, Tuple{Symbol}, NamedTuple{(:constant_lags,), Tuple{Tuple{Float64}}}})
>    @ SciMLBase ~/.julia/packages/SciMLBase/OfgnG/src/problems/sdde_problems.jl:147
>  [5] top-level scope
>    @ ~/testing_julia/test.jl:16

**Version Info**

> Julia Version 1.8.0
> Commit 5544a0fab76 (2022-08-17 13:38 UTC)

> status StochasticDelayDiffEq
> Status `~/.julia/environments/v1.8/Project.toml`
>   [29a0d76e] StochasticDelayDiffEq v1.2.2

**Comment by devmotion** [comment] 2022-08-19 20:16
I can't reproduce this issue, it works fine for me on Julia 1.8. I assume this was fixed by https://github.com/SciML/SciMLBase.jl/pull/220.

Feel free to reopen if the issue persists after updating SciMLBase.

**Closed by devmotion** 2022-08-19 20:16 UTC
